[project]
name = "rag-agent"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.10.0",
    "faiss-cpu>=1.12.0",
    "langchain-community>=0.3.27",
    "langgraph>=0.6.4",
    "pdfplumber>=0.11.7",
    "sentence-transformers>=5.1.0",
]
